### ISSUE TITLE
All the header is moving!

### ISSUE THREAD

**Issue by DevAbdoTolba** [BeshoyMarkElMallah/Agency-bootstrap#1]
Instead of adding padding when hovering on the nav item link, add a transform translateY effect with something like -6px.
With padding the whole header moves which makes the experience a little bit weird for the users

**Comment by BeshoyMarkElMallah** [comment]
where ??

**Comment by DevAbdoTolba** [comment]
All the pages in the nav bar there is the below problem :


https://github.com/BeshoyMarkElMallah/Agency-bootstrap/assets/100101090/d1d3bf26-9562-43d0-8e6e-bcc0b9e0c717


```
.header .navbar a:hover {
    color: var(--primary);
    border-bottom: 0.3rem solid var(--primary);
    transform: translateY(-10px);
}
```

it looks like this : 


https://github.com/BeshoyMarkElMallah/Agency-bootstrap/assets/100101090/b238f085-efca-4843-b931-c1291089b93b

Hope it fits you well ☺️
yours -Abdo Tolba

**Comment by BeshoyMarkElMallah** [comment]
thanks alot my friend
